### ISSUE TITLE
Clarify use of padding for tag 22

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#29] opened 2018-07-22 04:37 UTC
As illustrated in [this issue](https://github.com/peteroupc/CBOR/issues/14), my implementation does not write out padding by default when writing out tag 22 objects to JSON.  The implementation currently assumes that padding is omitted for base64 just as for base64url; however, since section 2.4.4.2 of the current CBOR RFC refers to RFC 4648, tag 22's traditional base64 seems to use padding since the description of tag 22 doesn't specify otherwise. Thus, section 3.4.4.2 of the CBOR revision should clarify whether tag 22 (traditional base64) uses padding or not.

**Comment by cabo** [comment] 2018-07-25 14:06
(Copying my comment from the issue on peteroupc/CBOR:)

thanks for bringing this up again.  We discussed this in the CBOR WG at iETF100 (
https://datatracker.ietf.org/meeting/100/materials/minutes-100-cbor/), but it seems we didn't reach a final conclusion.  Note that the issue is not really a CBOR one — the objective is to interoperate best with the JSON side, and we don't have a very good survey of what is the usual form of base64 on the JSON side.  (I have seen both the redundant base64 padding and no padding; while padding seems to be rare with base64url.)

So it would be most useful to collect some data before resolving this issue.

**Comment by paulehoffman** [comment] 2019-01-07 19:07
CBOR can specify to leave off padding.

**Comment by paulehoffman** [comment] 2019-01-14 17:41
Fixed in #48

**Comment by cabo** [comment] 2019-01-15 22:01
Note that #48 has changed a bit since yesterday — I actually checked recent RFCs that use base64 (as opposed to base64url) in JSON and they all use padding.  (Fortunately, all base64url usage is indeed without padding.)  So the pull request now reflects this and makes a few more clarifications.  Please check whether that answers your question.

**Comment by peteroupc** [comment] 2019-01-15 22:10
It appears to be fine by me.

**Closed** 2019-01-15 22:19 UTC
